/* Generated by the Nim Compiler v1.5.1 */
var framePtr = null;
var excHandler = 0;
var lastJSError = null;
var NTI33554456 = {size: 0,kind: 31,base: null,node: null,finalizer: null};
var NTI33555900 = {size: 0, kind: 18, base: null, node: null, finalizer: null};
var NTI33555069 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI33555151 = {size: 0, kind: 22, base: null, node: null, finalizer: null};
var NTI33554440 = {size: 0,kind: 29,base: null,node: null,finalizer: null};
var NTI33555150 = {size: 0, kind: 22, base: null, node: null, finalizer: null};
var NTI33555098 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI33555099 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI33555110 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI33554439 = {size: 0,kind: 28,base: null,node: null,finalizer: null};
var NNI33555110 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI33555110.node = NNI33555110;
var NNI33555099 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI33555099.node = NNI33555099;
NTI33555150.base = NTI33555098;
NTI33555151.base = NTI33555098;
var NNI33555098 = {kind: 2, len: 5, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "parent", len: 0, typ: NTI33555150, name: "parent", sons: null}, 
{kind: 1, offset: "name", len: 0, typ: NTI33554440, name: "name", sons: null}, 
{kind: 1, offset: "message", len: 0, typ: NTI33554439, name: "msg", sons: null}, 
{kind: 1, offset: "trace", len: 0, typ: NTI33554439, name: "trace", sons: null}, 
{kind: 1, offset: "up", len: 0, typ: NTI33555151, name: "up", sons: null}]};
NTI33555098.node = NNI33555098;
var NNI33555069 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI33555069.node = NNI33555069;
NTI33555098.base = NTI33555069;
NTI33555099.base = NTI33555098;
NTI33555110.base = NTI33555099;
var NNI33555900 = {kind: 2, len: 3, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "Field0", len: 0, typ: NTI33554440, name: "Field0", sons: null}, 
{kind: 1, offset: "Field1", len: 0, typ: NTI33554456, name: "Field1", sons: null}, 
{kind: 1, offset: "Field2", len: 0, typ: NTI33554440, name: "Field2", sons: null}]};
NTI33555900.node = NNI33555900;

function setConstr() {
        var result = {};
    for (var i = 0; i < arguments.length; ++i) {
      var x = arguments[i];
      if (typeof(x) == "object") {
        for (var j = x[0]; j <= x[1]; ++j) {
          result[j] = true;
        }
      } else {
        result[x] = true;
      }
    }
    return result;
  

  
}
var ConstSet1 = setConstr(17, 16, 4, 18, 27, 19, 23, 22, 21);

function nimCopy(dest_33557150, src_33557151, ti_33557152) {
  var result_33557161 = null;

    switch (ti_33557152.kind) {
    case 21:
    case 22:
    case 23:
    case 5:
      if (!(isFatPointer_33557141(ti_33557152))) {
      result_33557161 = src_33557151;
      }
      else {
        result_33557161 = [src_33557151[0], src_33557151[1]];
      }
      
      break;
    case 19:
            if (dest_33557150 === null || dest_33557150 === undefined) {
        dest_33557150 = {};
      }
      else {
        for (var key in dest_33557150) { delete dest_33557150[key]; }
      }
      for (var key in src_33557151) { dest_33557150[key] = src_33557151[key]; }
      result_33557161 = dest_33557150;
    
      break;
    case 18:
    case 17:
      if (!((ti_33557152.base == null))) {
      result_33557161 = nimCopy(dest_33557150, src_33557151, ti_33557152.base);
      }
      else {
      if ((ti_33557152.kind == 17)) {
      result_33557161 = (dest_33557150 === null || dest_33557150 === undefined) ? {m_type: ti_33557152} : dest_33557150;
      }
      else {
        result_33557161 = (dest_33557150 === null || dest_33557150 === undefined) ? {} : dest_33557150;
      }
      }
      nimCopyAux(result_33557161, src_33557151, ti_33557152.node);
      break;
    case 24:
    case 4:
    case 27:
    case 16:
            if (src_33557151 === null) {
        result_33557161 = null;
      }
      else {
        if (dest_33557150 === null || dest_33557150 === undefined) {
          dest_33557150 = new Array(src_33557151.length);
        }
        else {
          dest_33557150.length = src_33557151.length;
        }
        result_33557161 = dest_33557150;
        for (var i = 0; i < src_33557151.length; ++i) {
          result_33557161[i] = nimCopy(result_33557161[i], src_33557151[i], ti_33557152.base);
        }
      }
    
      break;
    case 28:
            if (src_33557151 !== null) {
        result_33557161 = src_33557151.slice(0);
      }
    
      break;
    default: 
      result_33557161 = src_33557151;
      break;
    }

  return result_33557161;

}

function makeNimstrLit(c_33556808) {
      var result = [];
  for (var i = 0; i < c_33556808.length; ++i) {
    result[i] = c_33556808.charCodeAt(i);
  }
  return result;
  

  
}

function arrayConstr(len_33557189, value_33557190, typ_33557191) {
        var result = new Array(len_33557189);
    for (var i = 0; i < len_33557189; ++i) result[i] = nimCopy(null, value_33557190, typ_33557191);
    return result;
  

  
}

function cstrToNimstr(c_33556811) {
      var ln = c_33556811.length;
  var result = new Array(ln);
  var r = 0;
  for (var i = 0; i < ln; ++i) {
    var ch = c_33556811.charCodeAt(i);

    if (ch < 128) {
      result[r] = ch;
    }
    else {
      if (ch < 2048) {
        result[r] = (ch >> 6) | 192;
      }
      else {
        if (ch < 55296 || ch >= 57344) {
          result[r] = (ch >> 12) | 224;
        }
        else {
            ++i;
            ch = 65536 + (((ch & 1023) << 10) | (c_33556811.charCodeAt(i) & 1023));
            result[r] = (ch >> 18) | 240;
            ++r;
            result[r] = ((ch >> 12) & 63) | 128;
        }
        ++r;
        result[r] = ((ch >> 6) & 63) | 128;
      }
      ++r;
      result[r] = (ch & 63) | 128;
    }
    ++r;
  }
  return result;
  

  
}

function toJSStr(s_33556814) {
                    var Temporary5;
            var Temporary7;

  var result_33556815 = null;

    var res_33556849 = newSeq_33556832((s_33556814).length);
    var i_33556850 = 0;
    var j_33556851 = 0;
    Label1: do {
        Label2: while (true) {
        if (!(i_33556850 < (s_33556814).length)) break Label2;
          var c_33556852 = s_33556814[i_33556850];
          if ((c_33556852 < 128)) {
          res_33556849[j_33556851] = String.fromCharCode(c_33556852);
          i_33556850 += 1;
          }
          else {
            var helper_33556864 = newSeq_33556832(0);
            Label3: do {
                Label4: while (true) {
                if (!true) break Label4;
                  var code_33556865 = c_33556852.toString(16);
                  if ((((code_33556865) == null ? 0 : (code_33556865).length) == 1)) {
                  helper_33556864.push("%0");;
                  }
                  else {
                  helper_33556864.push("%");;
                  }
                  
                  helper_33556864.push(code_33556865);;
                  i_33556850 += 1;
                    if (((s_33556814).length <= i_33556850)) Temporary5 = true; else {                      Temporary5 = (s_33556814[i_33556850] < 128);                    }                  if (Temporary5) {
                  break Label3;
                  }
                  
                  c_33556852 = s_33556814[i_33556850];
                }
            } while (false);
++excHandler;
            Temporary7 = framePtr;
            try {
            res_33556849[j_33556851] = decodeURIComponent(helper_33556864.join(""));
--excHandler;
} catch (EXCEPTION) {
 var prevJSError = lastJSError;
 lastJSError = EXCEPTION;
 --excHandler;
            framePtr = Temporary7;
            res_33556849[j_33556851] = helper_33556864.join("");
            lastJSError = prevJSError;
            } finally {
            framePtr = Temporary7;
            }
          }
          
          j_33556851 += 1;
        }
    } while (false);
    if (res_33556849.length < j_33556851) { for (var i = res_33556849.length ; i < j_33556851 ; ++i) res_33556849.push(null); }
               else { res_33556849.length = j_33556851; };
    result_33556815 = res_33556849.join("");

  return result_33556815;

}

function raiseException(e_33556675, ename_33556676) {
    e_33556675.name = ename_33556676;
    if ((excHandler == 0)) {
    unhandledException(e_33556675);
    }
    
    e_33556675.trace = nimCopy(null, rawWriteStackTrace_33556639(), NTI33554439);
    throw e_33556675;

  
}
if (!Math.trunc) {
  Math.trunc = function(v) {
    v = +v;
    if (!isFinite(v)) return v;
    return (v - v % 1) || (v < 0 ? -0 : v === 0 ? v : 0);
  };
}

var F = {procname: "module jsformdata", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/std/jsformdata.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsformdata", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/std/jsformdata.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsformdata", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/std/jsformdata.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsformdata", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/std/jsformdata.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsformdata", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/std/jsformdata.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsformdata", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/std/jsformdata.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsformdata", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/std/jsformdata.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsformdata", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/std/jsformdata.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsformdata", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/std/jsformdata.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsformdata", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/std/jsformdata.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsformdata", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/std/jsformdata.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsformdata", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/std/jsformdata.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsformdata", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/std/jsformdata.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsformdata", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/std/jsformdata.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsformdata", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/std/jsformdata.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsformdata", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/std/jsformdata.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsformdata", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/std/jsformdata.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsformdata", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/std/jsformdata.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsformdata", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/std/jsformdata.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsformdata", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/std/jsformdata.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsformdata_examples_1", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsformdata_examples_1.nim", line: 0};
framePtr = F;
framePtr = F.prev;

function isFatPointer_33557141(ti_33557142) {
  var result_33557143 = false;

  BeforeRet: do {
    result_33557143 = !((ConstSet1[ti_33557142.base.kind] != undefined));
    break BeforeRet;
  } while (false);

  return result_33557143;

}

function nimCopyAux(dest_33557154, src_33557155, n_33557156) {
    switch (n_33557156.kind) {
    case 0:
      break;
    case 1:
            dest_33557154[n_33557156.offset] = nimCopy(dest_33557154[n_33557156.offset], src_33557155[n_33557156.offset], n_33557156.typ);
    
      break;
    case 2:
          for (var i = 0; i < n_33557156.sons.length; i++) {
      nimCopyAux(dest_33557154, src_33557155, n_33557156.sons[i]);
    }
    
      break;
    case 3:
            dest_33557154[n_33557156.offset] = nimCopy(dest_33557154[n_33557156.offset], src_33557155[n_33557156.offset], n_33557156.typ);
      for (var i = 0; i < n_33557156.sons.length; ++i) {
        nimCopyAux(dest_33557154, src_33557155, n_33557156.sons[i][1]);
      }
    
      break;
    }

  
}

function add_33556416(x_33556417, x_33556417_Idx, y_33556418) {
          if (x_33556417[x_33556417_Idx] === null) { x_33556417[x_33556417_Idx] = []; }
      var off = x_33556417[x_33556417_Idx].length;
      x_33556417[x_33556417_Idx].length += y_33556418.length;
      for (var i = 0; i < y_33556418.length; ++i) {
        x_33556417[x_33556417_Idx][off+i] = y_33556418.charCodeAt(i);
      }
    

  
}

function auxWriteStackTrace_33556551(f_33556552) {
          var Temporary3;

  var result_33556553 = [[]];

    var it_33556561 = f_33556552;
    var i_33556562 = 0;
    var total_33556563 = 0;
    var tempFrames_33556564 = arrayConstr(64, {Field0: null, Field1: 0, Field2: null}, NTI33555900);
    Label1: do {
        Label2: while (true) {
          if (!!((it_33556561 == null))) Temporary3 = false; else {            Temporary3 = (i_33556562 <= 63);          }        if (!Temporary3) break Label2;
          tempFrames_33556564[i_33556562].Field0 = it_33556561.procname;
          tempFrames_33556564[i_33556562].Field1 = it_33556561.line;
          tempFrames_33556564[i_33556562].Field2 = it_33556561.filename;
          i_33556562 += 1;
          total_33556563 += 1;
          it_33556561 = it_33556561.prev;
        }
    } while (false);
    Label4: do {
        Label5: while (true) {
        if (!!((it_33556561 == null))) break Label5;
          total_33556563 += 1;
          it_33556561 = it_33556561.prev;
        }
    } while (false);
    result_33556553[0] = nimCopy(null, [], NTI33554439);
    if (!((total_33556563 == i_33556562))) {
    result_33556553[0].push.apply(result_33556553[0], makeNimstrLit("("));;
    result_33556553[0].push.apply(result_33556553[0], cstrToNimstr(((total_33556563 - i_33556562)) + ""));;
    result_33556553[0].push.apply(result_33556553[0], makeNimstrLit(" calls omitted) ...\x0A"));;
    }
    
    Label6: do {
      var j_33556610 = 0;
      var colontmp__520093731 = 0;
      colontmp__520093731 = (i_33556562 - 1);
      var res_520093733 = colontmp__520093731;
      Label7: do {
          Label8: while (true) {
          if (!(0 <= res_520093733)) break Label8;
            j_33556610 = res_520093733;
            result_33556553[0].push.apply(result_33556553[0], cstrToNimstr(tempFrames_33556564[j_33556610].Field2));;
            if ((0 < tempFrames_33556564[j_33556610].Field1)) {
            result_33556553[0].push.apply(result_33556553[0], makeNimstrLit("("));;
            result_33556553[0].push.apply(result_33556553[0], cstrToNimstr((tempFrames_33556564[j_33556610].Field1) + ""));;
            if (false) {
            result_33556553[0].push.apply(result_33556553[0], makeNimstrLit(", "));;
            result_33556553[0].push.apply(result_33556553[0], makeNimstrLit("0"));;
            }
            
            result_33556553[0].push.apply(result_33556553[0], makeNimstrLit(")"));;
            }
            
            result_33556553[0].push.apply(result_33556553[0], makeNimstrLit(" at "));;
            add_33556416(result_33556553, 0, tempFrames_33556564[j_33556610].Field0);
            result_33556553[0].push.apply(result_33556553[0], makeNimstrLit("\x0A"));;
            res_520093733 -= 1;
          }
      } while (false);
    } while (false);

  return result_33556553[0];

}

function rawWriteStackTrace_33556639() {
  var result_33556640 = [];

    if (!((framePtr == null))) {
    result_33556640 = nimCopy(null, (makeNimstrLit("Traceback (most recent call last)\x0A") || []).concat(auxWriteStackTrace_33556551(framePtr) || []), NTI33554439);
    }
    else {
      result_33556640 = nimCopy(null, makeNimstrLit("No stack traceback available\x0A"), NTI33554439);
    }
    

  return result_33556640;

}

function newSeq_33556832(len_33556834) {
  var result_33556835 = [];

  var F = {procname: "newSeq.newSeq", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/system.nim", line: 0};
  framePtr = F;
    F.line = 681;
    result_33556835 = new Array(len_33556834); for (var i = 0 ; i < len_33556834 ; ++i) { result_33556835[i] = null; }  framePtr = F.prev;

  return result_33556835;

}

function unhandledException(e_33556671) {
    var buf_33556672 = [[]];
    if (!(((e_33556671.message).length == 0))) {
    buf_33556672[0].push.apply(buf_33556672[0], makeNimstrLit("Error: unhandled exception: "));;
    buf_33556672[0].push.apply(buf_33556672[0], e_33556671.message);;
    }
    else {
    buf_33556672[0].push.apply(buf_33556672[0], makeNimstrLit("Error: unhandled exception"));;
    }
    
    buf_33556672[0].push.apply(buf_33556672[0], makeNimstrLit(" ["));;
    add_33556416(buf_33556672, 0, e_33556671.name);
    buf_33556672[0].push.apply(buf_33556672[0], makeNimstrLit("]\x0A"));;
    buf_33556672[0].push.apply(buf_33556672[0], rawWriteStackTrace_33556639());;
    var cbuf_33556673 = toJSStr(buf_33556672[0]);
    framePtr = null;
      if (typeof(Error) !== "undefined") {
    throw new Error(cbuf_33556673);
  }
  else {
    throw cbuf_33556673;
  }
  

  
}

function sysFatal_218103844(message_218103847) {
  var F = {procname: "sysFatal.sysFatal", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/system/fatal.nim", line: 0};
  framePtr = F;
    F.line = 53;
    raiseException({message: nimCopy(null, message_218103847, NTI33554439), m_type: NTI33555110, parent: null, name: null, trace: [], up: null}, "AssertionDefect");
  framePtr = F.prev;

  
}

function raiseAssert_218103842(msg_218103843) {
  var F = {procname: "assertions.raiseAssert", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/system/assertions.nim", line: 0};
  framePtr = F;
    F.line = 29;
    sysFatal_218103844(msg_218103843);
  framePtr = F.prev;

  
}

function failedAssertImpl_218103866(msg_218103867) {
  var F = {procname: "assertions.failedAssertImpl", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/system/assertions.nim", line: 0};
  framePtr = F;
    F.line = 39;
    raiseAssert_218103842(msg_218103867);
  framePtr = F.prev;

  
}
var F = {procname: "module jsformdata_examples_1", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsformdata_examples_1.nim", line: 0};
framePtr = F;
F.line = 57;
var data_520093698 = new FormData();
F.line = 57;
data_520093698.set("key0", "value0");
F.line = 57;
data_520093698.append("key1", "value1");
F.line = 57;
data_520093698.delete("key1");
if (!(data_520093698.has("key0"))) {
F.line = 57;
failedAssertImpl_218103866(makeNimstrLit("/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsformdata_examples_1.nim(12, 10) `data.hasKey(\"key0\")` "));
}

if (!((data_520093698.get("key0") == "value0"))) {
F.line = 57;
failedAssertImpl_218103866(makeNimstrLit("/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsformdata_examples_1.nim(13, 10) `data[\"key0\"] == \"value0\".cstring` "));
}

F.line = 57;
(() => { const frmdt = data_520093698; Array.from(frmdt.keys()).forEach((key) => frmdt.delete(key)) })();
if (!((Array.from(data_520093698.entries()).length == 0))) {
F.line = 57;
failedAssertImpl_218103866(makeNimstrLit("/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsformdata_examples_1.nim(15, 10) `data.len == 0` "));
}

framePtr = F.prev;
var F = {procname: "module jsformdata_examples_1", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsformdata_examples_1.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsformdata_examples_1", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsformdata_examples_1.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsformdata_group0_examples", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsformdata_group0_examples.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsformdata_group0_examples", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsformdata_group0_examples.nim", line: 0};
framePtr = F;
framePtr = F.prev;
